name: Run React Native tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable
        shell: bash

      - name: Use correct Yarn version
        run: corepack prepare yarn@4.6.0 --activate
        shell: bash

      - name: Install dependencies
        run: yarn install --immutable
        shell: bash

      - name: Run lint
        run: yarn eslint .
        shell: bash

      - name: Check typescript
        run: yarn tsc
        shell: bash
